Controllers/ContactUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pharmecy1Web.Controllers
{
    public class ContactUsController : Controller
    {
        // GET: ContactUs
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pharmecy1Web.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/QuoteUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pharmecy1Web.Controllers
{
    public class QuoteUsController : Controller
    {
        // GET: QuoteUs
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pharmecy1Web.Controllers
{
    public class RegisterController : Controller
    {
        // GET: Register
        public ActionResult Index()
        {
            return View();
        }
    }
}

Views/Header/HeaderLayout.cshtml
@*@{
    ViewBag.Title = "Header";
}*@

<div class="container">
    <div class="h_menu4">
        <ul class="memenu skyblue">
            <li class="showhide" style="display: none;"><span class="title">MENU</span><span class="icon1"></span><span class="icon2"></span></li>
            <li class="active grid" style="display: inline;"><a class="color8" href="@Url.Action("Index","Home")">Home</a></li>
            <li class="grid" style="display: inline;">
                <a class="color2" href="#">	About Us</a>
                <div class="mepanel">
                    <div class="row">

                    </div>
                </div>
            </li>
            <li style="display: inline;"><a class="color4" href="@Url.Action("Product","Home")">Products</a></li>
            <li style="display: inline;"><a class="color6" href="@Url.Action("Index","ContactUs")">Contact US</a></li>
            <li style="display: inline;"><a class="color6" href="@Url.Action("Index","QuoteUs")">Quote US</a></li>
            <li style="display: inline;"><a class="color6" href="@Url.Action("Index","Carrer")">Carrer</a></li>
            <li style="display: inline;"><a class="color6" id="btnDangNhap" href="@Url.Action("Index","Login")">Login</a></li>
            <li style="display: inline;"><a class="color6" id="btnDangKi" href="@Url.Action("Index","Register")">Register</a></li>
        </ul>
    </div>

</div>